### ISSUE TITLE
Artifact upload status check error

### ISSUE THREAD

**Issue by pbalawender** [agonsant/web-nexus-deployer#2]
I'm using web-nexus-deployer to upload single artifact into repository. When running it locally everything works fine. When I tried to make Bamboo job to do I have an error like below: 
`error	08-Aug-2017 16:41:45	F:\bwdir\xxx\node_modules\web-nexus-deployer\tasks\lib\index.js:106`
`error	08-Aug-2017 16:41:45	                if ((status && status.substring(0, 1) == "2") || code == 0) {`
`error	08-Aug-2017 16:41:45 ...............^`
`error	08-Aug-2017 16:41:45	TypeError: status.substring is not a function`
`error	08-Aug-2017 16:41:45	    at ChildProcess.<anonymous> (F:\bwdir\xxx\node_modules\web-nexus-deployer\tasks\lib\index.js:106:39)`
`error	08-Aug-2017 16:41:45	    at emitTwo (events.js:111:20)`
`error	08-Aug-2017 16:41:45	    at ChildProcess.emit (events.js:191:7)`
`error	08-Aug-2017 16:41:45	    at maybeClose (internal/child_process.js:852:16)`
`error	08-Aug-2017 16:41:45	    at Socket.<anonymous> (internal/child_process.js:323:11)`
`error	08-Aug-2017 16:41:45	    at emitOne (events.js:96:13)`
`error	08-Aug-2017 16:41:45	    at Socket.emit (events.js:188:7)`
`error	08-Aug-2017 16:41:45	    at Pipe._handle.close [as _onclose] (net.js:492:12)`

I have done some debugging and it looks like _status_ is an _object_ not _string_ (I've used typeof on it).
`[onClose] code: 0 type number status: 201 type object`
The simplest solution in my opinion is to do _toString()_ on this _status_ object.

**Comment by agonsant** [comment]
Hi,

First of all thank you for use the library.
I'll try to reproduce the issue in order to understand why it is returning an object instead a String.

**Comment by agonsant** [comment]
I've not been able to reproduce the issue. I've installed Bamboo in a Windows-64-bits and  Linux environments and I've created a Bamboo job with the next tasks:

1. npm install task
2. gulp deploy-nexus task (Executing a web nexus deployer gulp task i have created for testing the issue)

@pbalawender Could you please give some extra information?

- Platform environment
- Nexus version where you deploy your files.
- Curl version where Bamboo server is installed.

Thanks in advance!

.

**Comment by pbalawender** [comment]
@agonsant thank you for your response. Unfortunately my application is build and deployed on client infrastructure. I don't have administrator permissions, but this is what I was able to gather:
Nexus version: 2.11.4
curl version: 7.45.0
Bamboo (v. 5.14.1) is running on Windows, but I wasn't able to determinate exact version.

**Comment by agonsant** [comment]
@pbalawender,  I could not reproduce the issue but i fixed using toString() in received status. I will create the release 1.0.2, please let me know if the issue was resolved.

Thanks

**Comment by pbalawender** [comment]
@agonsant It worked! Thank you very much.
